// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bilginyuksel/trade/internal/order (interfaces: CurrencyConverter)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCurrencyConverter is a mock of CurrencyConverter interface.
type MockCurrencyConverter struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyConverterMockRecorder
}

// MockCurrencyConverterMockRecorder is the mock recorder for MockCurrencyConverter.
type MockCurrencyConverterMockRecorder struct {
	mock *MockCurrencyConverter
}

// NewMockCurrencyConverter creates a new mock instance.
func NewMockCurrencyConverter(ctrl *gomock.Controller) *MockCurrencyConverter {
	mock := &MockCurrencyConverter{ctrl: ctrl}
	mock.recorder = &MockCurrencyConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyConverter) EXPECT() *MockCurrencyConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockCurrencyConverter) Convert(arg0 context.Context, arg1, arg2 string, arg3 float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockCurrencyConverterMockRecorder) Convert(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockCurrencyConverter)(nil).Convert), arg0, arg1, arg2, arg3)
}
